"""Held-out acceptance suite for shd-007 W4. DO NOT EDIT THIS FILE."""

import pytest

from roster.parser import parse, Shift
from roster.report import build_report, totals_by_person
from roster.rules import rest_violations, consecutive_day_violations


def test_plain_shift_length():
    (s,) = parse("Ana,0,9-17")
    assert (s.start, s.end) == (9, 17)
    assert s.hours == 8


def test_wrapping_shift_length():
    (s,) = parse("Ana,0,22-6")
    assert s.hours == 8
    assert s.end_abs == 30


def test_rest_after_a_wrapping_shift_is_a_violation():
    # Ana finishes Tuesday 06:00 and restarts Tuesday 10:00 -- four hours' rest.
    shifts = parse("Ana,0,22-6\nAna,1,10-18")
    assert len(rest_violations(shifts)) == 1


def test_adequate_rest_is_not_a_violation():
    shifts = parse("Ana,0,9-17\nAna,1,9-17")
    assert rest_violations(shifts) == []


def test_names_are_case_insensitive():
    shifts = parse("Ana,0,9-17\nana,1,9-17")
    assert totals_by_person(shifts) == {"Ana": 16}


def test_consecutive_days():
    spec = "\n".join(f"Ana,{d},9-17" for d in range(6))
    assert consecutive_day_violations(parse(spec)) == ["Ana"]


def test_five_days_is_allowed():
    spec = "\n".join(f"Ana,{d},9-17" for d in range(5))
    assert consecutive_day_violations(parse(spec)) == []


def test_full_report():
    spec = """
    Ana,0,22-6
    ana,1,14-22
    Bo,0,9-17
    Bo,1,9-17
    """
    r = build_report(parse(spec))
    assert r["totals"] == {"Ana": 16, "Bo": 16}
    assert r["busiest"] == "Ana"
    assert r["overworked"] == []
